### ISSUE TITLE
Warc resources not loading

### ISSUE THREAD

**Issue by obrienben** [nla/tinycdxserver#3]
I'm having trouble with a lot of resources not loading when using tinyCDXserver with OpenWayback 2.2.
So far I can query the CDX fine through OpenWayback, and it appears to load the html of the page, but all the subsequent calls for the resources are not being found (css, js, images etc). A sample of my OpenWayback output

``
Feb 03, 2016 11:57:26 AM org.archive.wayback.resourceindex.RemoteResourceIndex$1 initialValue
SEVERE: Builder is not namespace aware.
Feb 03, 2016 11:57:26 AM org.archive.wayback.resourceindex.RemoteResourceIndex$1 initialValue
SEVERE: Builder is not namespace aware.
Feb 03, 2016 11:57:26 AM org.archive.wayback.resourceindex.RemoteResourceIndex$1 initialValue
SEVERE: Builder is not namespace aware.
Feb 03, 2016 11:57:26 AM org.archive.wayback.resourceindex.RemoteResourceIndex$1 initialValue
SEVERE: Builder is not namespace aware.
Feb 03, 2016 11:57:27 AM org.archive.wayback.webapp.AccessPoint handleReplay
INFO: LOADFAIL: Timeout: Too many retries, limited to 0
Feb 03, 2016 11:57:27 AM org.archive.wayback.webapp.AccessPoint handleReplay
WARNING: (1)LOADFAIL: Self-Redirect: No Closest Match Found /20151108060052/http://www.oversixty.co.nz/ui/css/fonts.css
Feb 03, 2016 11:57:27 AM org.archive.wayback.webapp.AccessPoint logError
WARNING: Runtime Error
org.archive.wayback.exception.ResourceNotAvailableException: Self-Redirect: No Closest Match Found
        at org.archive.wayback.webapp.AccessPoint.handleReplay(AccessPoint.java:811)
        at org.archive.wayback.webapp.AccessPoint.handleRequest(AccessPoint.java:313)
        at org.archive.wayback.util.webapp.RequestMapper.handleRequest(RequestMapper.java:198)
        at org.archive.wayback.util.webapp.RequestFilter.doFilter(RequestFilter.java:146)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:225)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:927)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:999)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:565)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:309)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
``

I can see the resources in the CDX file, and when I switch to using the same CDX as a localcdxcollection all the resources load fine.
Two things in the log caught my eye but I'm not sure if they are just red herrings:

- SEVERE: Builder is not namespace aware.

- INFO: LOADFAIL: Timeout: Too many retries, limited to 0

Have you guys come across this at all? Is there any configuration that I might be missing (retry limits, namespaces)?
Any help would be much appreciated.

**Comment by ato** [comment]
Unfortunately RemoteResourceIndex was broken in OpenWayback 2.1 and  2.2. It's a thread-safety problem which is why the first html request works and then the parallel requests loading images, css etc fail.

I submitted a patch to fix it which will be included in the OpenWayback 2.3 release, see iipc/openwayback#239.

It looks like there's an OpenWayback release candidate 2.3.RC.1 out now that should include it. I've just updated the tinycdxserver README to reflect that. I haven't tested 2.3.RC.1 myself yet, we're still running 2.1 plus the patch but I'm not aware of any reason why it wouldn't work. If you can't upgrade to 2.3.RC.1 you should be able to grab the patch from the pull request and apply it to 2.2.

**Comment by ato** [comment]
Ah, looks like the [2.3 final release](https://github.com/iipc/openwayback/releases) is out too. I missed it on the releases page as 2.3.RC.1 is highlighted in a much larger font. ;-)

**Comment by obrienben** [comment]
Great, just built 2.3 and its working now. Thanks for the quick reply :)
You mention in the readme that you're using it "under a relatively light traffic load", have you managed to do any stress testing?

**Comment by ato** [comment]
Alas, nothing particularly scientific or quantitive. I'd like to do an apples to apples comparison with CDX files at some point but haven't gotten around to it yet.

Our largest index currently in tinycdxserver is 700GB with about 7 billion records. We have the index files sitting on a RAID array of a few consumer-level SSDs. Hitting tinycdxserver directly with siege I'm seeing around 3,000 queries per second. That's with a warm cache though and only 10,000 unique query urls so it's probably not hitting the disk.

For indexing it's much faster than the reading of the WARC files so that hasn't been a concern for us.

**Comment by anjackson** [comment]
Is that 7 billion CDX lines? Or 7 billion individual field values?

**Comment by ato** [comment]
7 billion CDX lines
